"""add_fit_modality_and_fluorescence_columns

Add fit_modality domain discriminator, center_nm/fwhm_nm for fluorescence,
relax center_cm1/fwhm_cm1 nullability, remove duplicate indexes.

Revision ID: 6cff8ea9cb06
Revises: cd1b1897542e
Create Date: 2026-02-06 22:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cff8ea9cb06'
down_revision: Union[str, Sequence[str], None] = 'cd1b1897542e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add fit_modality, center_nm, fwhm_nm, is_saturated columns.

    Phase 1: Add columns with server_default to backfill existing rows.
    Phase 2: Remove server_default so future inserts require explicit fit_modality.
    Phase 3: Add triggers for valid fit_modality values.
    """
    # Phase 1: Add columns, relax nullability, fix indexes
    with op.batch_alter_table('fitted_peaks', schema=None) as batch_op:
        # Add new columns (server_default backfills the 100 existing mineral rows)
        batch_op.add_column(sa.Column('fit_modality', sa.String(20),
                                       nullable=False, server_default='minerals'))
        batch_op.add_column(sa.Column('center_nm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fwhm_nm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_saturated', sa.Boolean(), nullable=True))

        # Relax nullability on cm1 columns (for fluorescence rows)
        batch_op.alter_column('center_cm1', nullable=True)
        batch_op.alter_column('fwhm_cm1', nullable=True)

        # Remove duplicate indexes
        batch_op.drop_index('ix_fitted_peaks_center_range')
        batch_op.drop_index('ix_fitted_peaks_mineral')

        # Add new indexes
        batch_op.create_index('ix_fitted_peaks_fit_modality', ['fit_modality'])
        batch_op.create_index('ix_fitted_peaks_center_nm', ['center_nm'])
        batch_op.create_index('ix_fitted_peaks_modality_assignment',
                              ['fit_modality', 'mineral_assignment'])

    # Phase 2: Remove server_default so future inserts without fit_modality fail
    with op.batch_alter_table('fitted_peaks', schema=None) as batch_op:
        batch_op.alter_column('fit_modality', server_default=None)

    # Phase 3: Add triggers for valid fit_modality values (INSERT and UPDATE)
    op.execute("""
        CREATE TRIGGER IF NOT EXISTS check_fit_modality_insert
        BEFORE INSERT ON fitted_peaks
        BEGIN
            SELECT RAISE(ABORT, 'invalid fit_modality value')
            WHERE NEW.fit_modality NOT IN ('minerals', 'organics', 'hydration', 'fluorescence');
        END
    """)
    op.execute("""
        CREATE TRIGGER IF NOT EXISTS check_fit_modality_update
        BEFORE UPDATE OF fit_modality ON fitted_peaks
        BEGIN
            SELECT RAISE(ABORT, 'invalid fit_modality value')
            WHERE NEW.fit_modality NOT IN ('minerals', 'organics', 'hydration', 'fluorescence');
        END
    """)


def downgrade() -> None:
    """Reverse the fit_modality migration.

    Purges fluorescence rows first (they have NULL cm1 columns which
    would violate restored NOT NULL constraints). Fluorescence data can
    be regenerated by re-running ``sherloc fit-fluor --all``.
    """
    # Purge fluorescence rows before restoring NOT NULL constraints
    op.execute("DELETE FROM fitted_peaks WHERE fit_modality = 'fluorescence'")
    op.execute("DROP TRIGGER IF EXISTS check_fit_modality_insert")
    op.execute("DROP TRIGGER IF EXISTS check_fit_modality_update")

    with op.batch_alter_table('fitted_peaks', schema=None) as batch_op:
        batch_op.drop_index('ix_fitted_peaks_modality_assignment')
        batch_op.drop_index('ix_fitted_peaks_center_nm')
        batch_op.drop_index('ix_fitted_peaks_fit_modality')

        batch_op.create_index('ix_fitted_peaks_mineral', ['mineral_assignment'])
        batch_op.create_index('ix_fitted_peaks_center_range', ['center_cm1'])

        batch_op.alter_column('fwhm_cm1', nullable=False)
        batch_op.alter_column('center_cm1', nullable=False)

        batch_op.drop_column('is_saturated')
        batch_op.drop_column('fwhm_nm')
        batch_op.drop_column('center_nm')
        batch_op.drop_column('fit_modality')
