"""Initial PHASE schema with all tables

Revision ID: c8d2a36d1083
Revises: 
Create Date: 2026-01-23 18:54:01.194972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c8d2a36d1083'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sols',
    sa.Column('sol_number', sa.Integer(), nullable=False),
    sa.Column('earth_date', sa.Date(), nullable=True),
    sa.Column('solar_longitude', sa.Float(), nullable=True),
    sa.Column('mission_phase', sa.String(length=100), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('sol_number')
    )
    op.create_table('scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sol_number', sa.Integer(), nullable=False),
    sa.Column('target_name', sa.String(length=200), nullable=False),
    sa.Column('scan_id', sa.String(length=200), nullable=False),
    sa.Column('sclk_start', sa.Integer(), nullable=False),
    sa.Column('sclk_stop', sa.Integer(), nullable=True),
    sa.Column('n_points', sa.Integer(), nullable=False),
    sa.Column('n_channels', sa.Integer(), nullable=False),
    sa.Column('shots_per_point', sa.Integer(), nullable=False),
    sa.Column('laser_wavelength_nm', sa.Float(), nullable=False),
    sa.Column('processing_applied', sa.String(length=100), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('loupe_metadata', sqlite.JSON(), nullable=True),
    sa.Column('pds4_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sol_number'], ['sols.sol_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index('ix_scans_sclk', ['sclk_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_sol_number'), ['sol_number'], unique=False)
        batch_op.create_index('ix_scans_sol_target', ['sol_number', 'target_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_target_name'), ['target_name'], unique=False)

    op.create_table('ccd_configurations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('region_enable', sa.Integer(), nullable=True),
    sa.Column('gain_2d', sa.Integer(), nullable=True),
    sa.Column('mode_2d', sa.Integer(), nullable=True),
    sa.Column('vert_col1_low', sa.Integer(), nullable=True),
    sa.Column('vert_col1_high', sa.Integer(), nullable=True),
    sa.Column('vert_col2_low', sa.Integer(), nullable=True),
    sa.Column('vert_col2_high', sa.Integer(), nullable=True),
    sa.Column('vert_col3_low', sa.Integer(), nullable=True),
    sa.Column('vert_col3_high', sa.Integer(), nullable=True),
    sa.Column('horz_clock_lim', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ccd_configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ccd_configurations_scan_id'), ['scan_id'], unique=True)

    op.create_table('context_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('image_type', sa.String(length=10), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=True),
    sa.Column('sclk', sa.Integer(), nullable=True),
    sa.Column('pixel_scale_um', sa.Float(), nullable=True),
    sa.Column('working_distance_cm', sa.Float(), nullable=True),
    sa.Column('motor_position', sa.Integer(), nullable=True),
    sa.Column('exposure_time_ms', sa.Float(), nullable=True),
    sa.Column('led_illumination', sa.Boolean(), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_images_scan_id'), ['scan_id'], unique=False)

    op.create_table('instrument_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('ccd_temp_c', sa.Float(), nullable=True),
    sa.Column('pcb_temp_c', sa.Float(), nullable=True),
    sa.Column('laser_prt1_c', sa.Float(), nullable=True),
    sa.Column('laser_prt2_c', sa.Float(), nullable=True),
    sa.Column('laser_shot_counter', sa.Integer(), nullable=True),
    sa.Column('laser_misfire_counter', sa.Integer(), nullable=True),
    sa.Column('arc_event_counter', sa.Integer(), nullable=True),
    sa.Column('voltage_1_2v', sa.Float(), nullable=True),
    sa.Column('voltage_3_3v', sa.Float(), nullable=True),
    sa.Column('voltage_5v_dac', sa.Float(), nullable=True),
    sa.Column('voltage_5v_adc', sa.Float(), nullable=True),
    sa.Column('voltage_15v', sa.Float(), nullable=True),
    sa.Column('voltage_neg_15v', sa.Float(), nullable=True),
    sa.Column('laser_int_time_us', sa.Integer(), nullable=True),
    sa.Column('laser_rep_rate_hz', sa.Integer(), nullable=True),
    sa.Column('laser_current_a', sa.Float(), nullable=True),
    sa.Column('full_telemetry', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instrument_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instrument_states_scan_id'), ['scan_id'], unique=True)

    op.create_table('regions_of_interest',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('point_indices', sqlite.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regions_of_interest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regions_of_interest_scan_id'), ['scan_id'], unique=False)

    op.create_table('scan_points',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('point_index', sa.Integer(), nullable=False),
    sa.Column('azimuth_dn', sa.Integer(), nullable=True),
    sa.Column('elevation_dn', sa.Integer(), nullable=True),
    sa.Column('x_pixel', sa.Float(), nullable=True),
    sa.Column('y_pixel', sa.Float(), nullable=True),
    sa.Column('azimuth_error', sa.Float(), nullable=True),
    sa.Column('elevation_error', sa.Float(), nullable=True),
    sa.Column('photodiode_mean', sa.Float(), nullable=True),
    sa.Column('photodiode_std', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_points_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index('ix_scan_points_scan_index', ['scan_id', 'point_index'], unique=False)

    op.create_table('scanner_calibrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('az_scale', sa.Float(), nullable=False),
    sa.Column('el_scale', sa.Float(), nullable=False),
    sa.Column('laser_x', sa.Integer(), nullable=False),
    sa.Column('laser_y', sa.Integer(), nullable=False),
    sa.Column('rotation_deg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scanner_calibrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scanner_calibrations_scan_id'), ['scan_id'], unique=True)

    op.create_table('spectra',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_point_id', sa.String(length=36), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('spectrum_type', sa.String(length=20), nullable=False),
    sa.Column('processing_level', sa.String(length=20), nullable=False),
    sa.Column('intensities', sa.LargeBinary(), nullable=False),
    sa.Column('wavelengths', sa.LargeBinary(), nullable=True),
    sa.Column('wavenumbers', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_point_id'], ['scan_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spectra', schema=None) as batch_op:
        batch_op.create_index('ix_spectra_point_region_type', ['scan_point_id', 'region', 'spectrum_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_spectra_scan_point_id'), ['scan_point_id'], unique=False)

    op.create_table('fitted_peaks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('spectrum_id', sa.String(length=36), nullable=False),
    sa.Column('peak_type', sa.String(length=20), nullable=False),
    sa.Column('center_cm1', sa.Float(), nullable=False),
    sa.Column('center_uncertainty', sa.Float(), nullable=True),
    sa.Column('amplitude', sa.Float(), nullable=False),
    sa.Column('amplitude_uncertainty', sa.Float(), nullable=True),
    sa.Column('fwhm_cm1', sa.Float(), nullable=False),
    sa.Column('fwhm_uncertainty', sa.Float(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('snr', sa.Float(), nullable=True),
    sa.Column('fit_quality', sa.Float(), nullable=True),
    sa.Column('mineral_assignment', sa.String(length=100), nullable=True),
    sa.Column('assignment_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['spectrum_id'], ['spectra.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fitted_peaks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fitted_peaks_center_cm1'), ['center_cm1'], unique=False)
        batch_op.create_index('ix_fitted_peaks_center_range', ['center_cm1'], unique=False)
        batch_op.create_index('ix_fitted_peaks_mineral', ['mineral_assignment'], unique=False)
        batch_op.create_index(batch_op.f('ix_fitted_peaks_mineral_assignment'), ['mineral_assignment'], unique=False)
        batch_op.create_index(batch_op.f('ix_fitted_peaks_spectrum_id'), ['spectrum_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitted_peaks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fitted_peaks_spectrum_id'))
        batch_op.drop_index(batch_op.f('ix_fitted_peaks_mineral_assignment'))
        batch_op.drop_index('ix_fitted_peaks_mineral')
        batch_op.drop_index('ix_fitted_peaks_center_range')
        batch_op.drop_index(batch_op.f('ix_fitted_peaks_center_cm1'))

    op.drop_table('fitted_peaks')
    with op.batch_alter_table('spectra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spectra_scan_point_id'))
        batch_op.drop_index('ix_spectra_point_region_type')

    op.drop_table('spectra')
    with op.batch_alter_table('scanner_calibrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scanner_calibrations_scan_id'))

    op.drop_table('scanner_calibrations')
    with op.batch_alter_table('scan_points', schema=None) as batch_op:
        batch_op.drop_index('ix_scan_points_scan_index')
        batch_op.drop_index(batch_op.f('ix_scan_points_scan_id'))

    op.drop_table('scan_points')
    with op.batch_alter_table('regions_of_interest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regions_of_interest_scan_id'))

    op.drop_table('regions_of_interest')
    with op.batch_alter_table('instrument_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instrument_states_scan_id'))

    op.drop_table('instrument_states')
    with op.batch_alter_table('context_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_images_scan_id'))

    op.drop_table('context_images')
    with op.batch_alter_table('ccd_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ccd_configurations_scan_id'))

    op.drop_table('ccd_configurations')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_target_name'))
        batch_op.drop_index('ix_scans_sol_target')
        batch_op.drop_index(batch_op.f('ix_scans_sol_number'))
        batch_op.drop_index('ix_scans_sclk')
        batch_op.drop_index(batch_op.f('ix_scans_scan_id'))

    op.drop_table('scans')
    op.drop_table('sols')
    # ### end Alembic commands ###
