"""Behavior-preserving extraction proof for ``apply_mask_replacement``.

The legacy replacement block of ``despike_r1_spectrum``
was extracted into ``apply_mask_replacement``; this battery proves the
extraction is behavior-preserving against vectors **pinned from the
pre-extraction legacy arithmetic** (computed at commit ccb4d27's
generation: ``s.loc[mask] = nan; s.interpolate(method, limit_direction=
"both")``) plus an inline legacy-arithmetic equivalence sweep.

Also pins one full ``despike_r1_spectrum`` end-to-end output digest from
the pre-extraction code, so the loop refactor itself is covered, not just
the helper.
"""

import hashlib

import numpy as np
import pandas as pd
import pytest

from sherloc_pipeline.core.preprocessing import (
    DespikeParams,
    apply_mask_replacement,
    despike_r1_spectrum,
)


def _legacy_replace(series: pd.Series, mask: pd.Series, method: str) -> pd.Series:
    """The pre-extraction replacement arithmetic, verbatim."""
    s = series.astype(float).copy()
    s.loc[mask] = np.nan
    return s.interpolate(method=method, limit_direction="both")


# Vectors pinned from the pre-extraction legacy arithmetic (generated by
# running the legacy block at the pre-refactor commit). DO NOT regenerate
# with post-extraction code — that would defeat the purpose of the pin.
PINNED_CASES = [
    # (name, values, mask, method, expected)
    (
        "leading_linear",
        [900.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0],
        [True, False, False, False, False, False, False, False],
        "linear",
        [10.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0],
    ),
    (
        "trailing_linear",
        [10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 950.0],
        [False, False, False, False, False, False, False, True],
        "linear",
        [10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 16.0],
    ),
    (
        "flat_interior_linear",
        [5.0, 5.0, 5.0, 5.0, 800.0, 5.0, 5.0, 5.0, 5.0],
        [False, False, False, False, True, False, False, False, False],
        "linear",
        [5.0] * 9,
    ),
    (
        "nearest",
        [10.0, 20.0, 999.0, 40.0, 50.0],
        [False, False, True, False, False],
        "nearest",
        [10.0, 20.0, 20.0, 40.0, 50.0],
    ),
    (
        "quadratic",
        [1.0, 4.0, 999.0, 16.0, 25.0, 36.0],
        [False, False, True, False, False, False],
        "quadratic",
        [1.0, 4.0, 8.999999999999998, 16.0, 25.0, 36.0],
    ),
    (
        "cubic",
        [1.0, 4.0, 999.0, 16.0, 25.0, 36.0],
        [False, False, True, False, False, False],
        "cubic",
        [1.0, 4.0, 8.999999999999998, 16.0, 25.0, 36.0],
    ),
    (
        "slinear",
        [1.0, 4.0, 999.0, 16.0, 25.0, 36.0],
        [False, False, True, False, False, False],
        "slinear",
        [1.0, 4.0, 10.0, 16.0, 25.0, 36.0],
    ),
    (
        "adjacent_run_linear",
        [10.0, 11.0, 700.0, 701.0, 14.0, 15.0],
        [False, False, True, True, False, False],
        "linear",
        [10.0, 11.0, 12.0, 13.0, 14.0, 15.0],
    ),
]


class TestPinnedVectors:
    @pytest.mark.parametrize(
        "name,values,mask,method,expected",
        PINNED_CASES,
        ids=[case[0] for case in PINNED_CASES],
    )
    def test_pinned_vector(self, name, values, mask, method, expected):
        out = apply_mask_replacement(pd.Series(values), np.array(mask), method)
        np.testing.assert_allclose(out.to_numpy(), expected, rtol=0, atol=0)

    def test_float_index_linear_vs_index_method(self):
        """'linear' ignores index spacing; 'index' honors it — both pinned
        from the legacy arithmetic on a non-default float index."""
        index = [0.5, 1.7, 4.0, 8.0, 16.0]
        values = pd.Series([10.0, 600.0, 14.0, 16.0, 18.0], index=index)
        mask = pd.Series([False, True, False, False, False], index=index)

        out_linear = apply_mask_replacement(values, mask, "linear")
        np.testing.assert_allclose(
            out_linear.to_numpy(), [10.0, 12.0, 14.0, 16.0, 18.0]
        )

        out_index = apply_mask_replacement(values, mask, "index")
        np.testing.assert_allclose(
            out_index.to_numpy(),
            [10.0, 11.371428571428572, 14.0, 16.0, 18.0],
        )


class TestLegacyEquivalenceSweep:
    """Randomized inline equivalence: helper output == verbatim legacy
    arithmetic, across methods, mask shapes, and index types."""

    @pytest.mark.parametrize(
        "method", ["linear", "nearest", "index", "slinear", "quadratic", "cubic"]
    )
    @pytest.mark.parametrize("index_kind", ["range", "float", "shifted_int"])
    def test_equivalence(self, method, index_kind):
        rng = np.random.default_rng(hash((method, index_kind)) % 2**32)
        n = 40
        values = 50.0 + 10.0 * rng.standard_normal(n)
        index = {
            "range": pd.RangeIndex(n),
            "float": pd.Index(np.cumsum(rng.uniform(0.5, 2.0, n))),
            "shifted_int": pd.Index(np.arange(100, 100 + n)),
        }[index_kind]
        series = pd.Series(values, index=index)

        mask_arr = np.zeros(n, dtype=bool)
        mask_arr[rng.choice(n, size=5, replace=False)] = True
        mask = pd.Series(mask_arr, index=index)

        expected = _legacy_replace(series, mask, method)
        out = apply_mask_replacement(series, mask, method)
        pd.testing.assert_series_equal(out, expected)

    def test_exclusion_style_mask_equivalence(self):
        """Spikes adjacent to an excluded region (mask cleared there) —
        mirrors the active-exclusion shape from the despike loop."""
        n = 30
        values = pd.Series(np.linspace(10, 40, n))
        mask = np.zeros(n, dtype=bool)
        mask[[3, 4, 20]] = True
        mask[10:15] = False  # exclusion zone stays unflagged
        expected = _legacy_replace(values, pd.Series(mask), "linear")
        out = apply_mask_replacement(values, mask, "linear")
        pd.testing.assert_series_equal(out, expected)


class TestHelperContract:
    def test_empty_mask_returns_unchanged_and_preserves_nans(self):
        """An all-False mask must not interpolate pre-existing NaNs — the
        legacy loop broke before replacement when nothing was flagged."""
        values = pd.Series([1.0, np.nan, 3.0, 4.0])
        out = apply_mask_replacement(values, np.zeros(4, dtype=bool), "linear")
        assert np.isnan(out.iloc[1])
        np.testing.assert_array_equal(out.notna(), values.notna())
        assert out is not values  # still a copy

    def test_nonflagged_values_bitwise_unchanged(self):
        rng = np.random.default_rng(3)
        values = pd.Series(rng.standard_normal(50) * 1e3)
        mask = np.zeros(50, dtype=bool)
        mask[[7, 8, 31]] = True
        out = apply_mask_replacement(values, mask, "linear")
        np.testing.assert_array_equal(
            out.to_numpy()[~mask], values.to_numpy()[~mask]
        )

    def test_length_mismatch_raises(self):
        with pytest.raises(ValueError, match="length"):
            apply_mask_replacement(
                pd.Series([1.0, 2.0]), np.array([True]), "linear"
            )

    def test_series_mask_index_mismatch_raises(self):
        series = pd.Series([1.0, 2.0, 3.0], index=[0, 1, 2])
        mask = pd.Series([True, False, False], index=[5, 6, 7])
        with pytest.raises(ValueError, match="index"):
            apply_mask_replacement(series, mask, "linear")


class TestDespikeLoopRefactorPin:
    """End-to-end ``despike_r1_spectrum`` digest pinned from the
    pre-extraction code — proves the loop refactor (helper call site)
    is byte-identical, not just the helper in isolation."""

    def test_end_to_end_digest(self):
        rng = np.random.default_rng(7)
        n = 60
        y = 100.0 + 5.0 * np.sin(np.linspace(0, 6, n)) + rng.normal(0, 1.0, n)
        y[10] += 500.0
        y[11] += 480.0
        y[40] += 900.0
        raman = np.linspace(800.0, 1400.0, n)

        params = DespikeParams(
            window_size=7,
            zscore_threshold=6.0,
            max_iterations=2,
            interpolation_method="linear",
        )
        out, mask = despike_r1_spectrum(pd.Series(y), params, raman_shift=raman)

        assert list(np.where(mask.to_numpy())[0]) == [10, 11, 40]
        digest = hashlib.sha256(
            np.ascontiguousarray(out.to_numpy()).tobytes()
        ).hexdigest()
        assert digest == (
            "41df427714c1f98c082c942e0090f1e87e0439946aa6de6e5fea3fe689cc084f"
        )
